package servidor;

import java.util.ArrayList;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mrodrigues
 */
public class FrmPrincipal extends javax.swing.JFrame {

    CtrlServidor control;
    
    /**
     * Creates new form frmRna
     * @param control
     */
    public FrmPrincipal( CtrlServidor control ) {
        
        this.control = control;
        
        initComponents();
        this.setLocationRelativeTo(null);
        txtServidor.setText("Servidor conectado.\n");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoFase = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ck1 = new javax.swing.JCheckBox();
        ck2 = new javax.swing.JCheckBox();
        ck3 = new javax.swing.JCheckBox();
        ck4 = new javax.swing.JCheckBox();
        ck5 = new javax.swing.JCheckBox();
        ck6 = new javax.swing.JCheckBox();
        ck7 = new javax.swing.JCheckBox();
        ck8 = new javax.swing.JCheckBox();
        ck9 = new javax.swing.JCheckBox();
        ck10 = new javax.swing.JCheckBox();
        ck11 = new javax.swing.JCheckBox();
        ck12 = new javax.swing.JCheckBox();
        ck13 = new javax.swing.JCheckBox();
        ck14 = new javax.swing.JCheckBox();
        ck15 = new javax.swing.JCheckBox();
        ck16 = new javax.swing.JCheckBox();
        ck17 = new javax.swing.JCheckBox();
        ck18 = new javax.swing.JCheckBox();
        ck19 = new javax.swing.JCheckBox();
        ck20 = new javax.swing.JCheckBox();
        ck21 = new javax.swing.JCheckBox();
        ck22 = new javax.swing.JCheckBox();
        ck23 = new javax.swing.JCheckBox();
        ck24 = new javax.swing.JCheckBox();
        ck25 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        radioExecucao = new javax.swing.JRadioButton();
        radioTreinamento = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtPadrao = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtServidor = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RNA - WiSARD [ maykelrodrigues@live.com ]");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parâmetros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 10))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pixels", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(5, 5));

        ck1.setMaximumSize(new java.awt.Dimension(61, 61));
        ck1.setMinimumSize(new java.awt.Dimension(61, 61));
        ck1.setPreferredSize(new java.awt.Dimension(61, 61));
        jPanel1.add(ck1);

        ck2.setMaximumSize(new java.awt.Dimension(31, 31));
        ck2.setMinimumSize(new java.awt.Dimension(31, 31));
        ck2.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck2);

        ck3.setMaximumSize(new java.awt.Dimension(31, 31));
        ck3.setMinimumSize(new java.awt.Dimension(31, 31));
        ck3.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck3);

        ck4.setMaximumSize(new java.awt.Dimension(31, 31));
        ck4.setMinimumSize(new java.awt.Dimension(31, 31));
        ck4.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck4);

        ck5.setMaximumSize(new java.awt.Dimension(31, 31));
        ck5.setMinimumSize(new java.awt.Dimension(31, 31));
        ck5.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck5);

        ck6.setMaximumSize(new java.awt.Dimension(31, 31));
        ck6.setMinimumSize(new java.awt.Dimension(31, 31));
        ck6.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck6);

        ck7.setMaximumSize(new java.awt.Dimension(31, 31));
        ck7.setMinimumSize(new java.awt.Dimension(31, 31));
        ck7.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck7);

        ck8.setMaximumSize(new java.awt.Dimension(31, 31));
        ck8.setMinimumSize(new java.awt.Dimension(31, 31));
        ck8.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck8);

        ck9.setMaximumSize(new java.awt.Dimension(31, 31));
        ck9.setMinimumSize(new java.awt.Dimension(31, 31));
        ck9.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck9);

        ck10.setMaximumSize(new java.awt.Dimension(31, 31));
        ck10.setMinimumSize(new java.awt.Dimension(31, 31));
        ck10.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck10);

        ck11.setMaximumSize(new java.awt.Dimension(31, 31));
        ck11.setMinimumSize(new java.awt.Dimension(31, 31));
        ck11.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck11);

        ck12.setMaximumSize(new java.awt.Dimension(31, 31));
        ck12.setMinimumSize(new java.awt.Dimension(31, 31));
        ck12.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck12);

        ck13.setMaximumSize(new java.awt.Dimension(31, 31));
        ck13.setMinimumSize(new java.awt.Dimension(31, 31));
        ck13.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck13);

        ck14.setMaximumSize(new java.awt.Dimension(31, 31));
        ck14.setMinimumSize(new java.awt.Dimension(31, 31));
        ck14.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck14);

        ck15.setMaximumSize(new java.awt.Dimension(31, 31));
        ck15.setMinimumSize(new java.awt.Dimension(31, 31));
        ck15.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck15);

        ck16.setMaximumSize(new java.awt.Dimension(31, 31));
        ck16.setMinimumSize(new java.awt.Dimension(31, 31));
        ck16.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck16);

        ck17.setMaximumSize(new java.awt.Dimension(31, 31));
        ck17.setMinimumSize(new java.awt.Dimension(31, 31));
        ck17.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck17);

        ck18.setMaximumSize(new java.awt.Dimension(31, 31));
        ck18.setMinimumSize(new java.awt.Dimension(31, 31));
        ck18.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck18);

        ck19.setMaximumSize(new java.awt.Dimension(31, 31));
        ck19.setMinimumSize(new java.awt.Dimension(31, 31));
        ck19.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck19);

        ck20.setMaximumSize(new java.awt.Dimension(31, 31));
        ck20.setMinimumSize(new java.awt.Dimension(31, 31));
        ck20.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck20);

        ck21.setMaximumSize(new java.awt.Dimension(31, 31));
        ck21.setMinimumSize(new java.awt.Dimension(31, 31));
        ck21.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck21);

        ck22.setMaximumSize(new java.awt.Dimension(31, 31));
        ck22.setMinimumSize(new java.awt.Dimension(31, 31));
        ck22.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck22);

        ck23.setMaximumSize(new java.awt.Dimension(31, 31));
        ck23.setMinimumSize(new java.awt.Dimension(31, 31));
        ck23.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck23);

        ck24.setMaximumSize(new java.awt.Dimension(31, 31));
        ck24.setMinimumSize(new java.awt.Dimension(31, 31));
        ck24.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck24);

        ck25.setMaximumSize(new java.awt.Dimension(31, 31));
        ck25.setMinimumSize(new java.awt.Dimension(31, 31));
        ck25.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(ck25);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fase", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        grupoFase.add(radioExecucao);
        radioExecucao.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        radioExecucao.setText("Execução");
        radioExecucao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioExecucaoStateChanged(evt);
            }
        });
        jPanel3.add(radioExecucao, java.awt.BorderLayout.CENTER);

        grupoFase.add(radioTreinamento);
        radioTreinamento.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        radioTreinamento.setSelected(true);
        radioTreinamento.setText("Treinamento");
        jPanel3.add(radioTreinamento, java.awt.BorderLayout.PAGE_START);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("Padrão:");

        btnEnviar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resultado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(4);
        jScrollPane1.setViewportView(txtResultado);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnLimpar)
                                .addComponent(btnEnviar))
                            .addComponent(txtPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servidor", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 10))); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        txtServidor.setEditable(false);
        txtServidor.setColumns(20);
        txtServidor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtServidor.setRows(5);
        jScrollPane2.setViewportView(txtServidor);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rede Neural Artificial - WiSARD");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("- Sistemas Distribuídos -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        limparDados();
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
       
       boolean fase = radioTreinamento.isSelected(); 
       String padrao = txtPadrao.getText();  
       
       if ( control.criarPacote(gerarVetor(), fase, padrao) ) { 
            txtServidor.append("Dados enviados...\n");
            limparDados();
       } else {
            txtServidor.append("Problema ao enviar os dados.\n");
       } 
       
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void radioExecucaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioExecucaoStateChanged
        
        if ( radioExecucao.isSelected()) txtPadrao.setEnabled(false); 
        else txtPadrao.setEnabled(true);
        
    }//GEN-LAST:event_radioExecucaoStateChanged

    public void appendServidor(String m) {
        txtServidor.append(m + "\n");
    }
    
    public void clearServidor() {
        txtServidor.setText("");
    }
    
    private void limparDados() {
        
        ck1.setSelected(false);
        ck2.setSelected(false);
        ck3.setSelected(false);
        ck4.setSelected(false);
        ck5.setSelected(false);
        ck6.setSelected(false);
        ck7.setSelected(false);
        ck8.setSelected(false);
        ck9.setSelected(false);
        ck10.setSelected(false);
        ck11.setSelected(false);
        ck12.setSelected(false);
        ck13.setSelected(false);
        ck14.setSelected(false);
        ck15.setSelected(false);
        ck16.setSelected(false);
        ck17.setSelected(false);
        ck18.setSelected(false);
        ck19.setSelected(false);
        ck20.setSelected(false);
        ck21.setSelected(false);
        ck22.setSelected(false);
        ck23.setSelected(false);
        ck24.setSelected(false);
        ck25.setSelected(false);
        txtPadrao.setText("");
        txtResultado.setText("");
        radioTreinamento.setSelected(true);
        
    }
    private ArrayList gerarVetor() {
        
        ArrayList array = new ArrayList();
        
        array.add( ck1.isSelected() == true ? 1 : 0 );
        array.add( ck2.isSelected() == true ? 1 : 0 );
        array.add( ck3.isSelected() == true ? 1 : 0 );
        array.add( ck4.isSelected() == true ? 1 : 0 );
        array.add( ck5.isSelected() == true ? 1 : 0 );
        array.add( ck6.isSelected() == true ? 1 : 0 );
        array.add( ck7.isSelected() == true ? 1 : 0 );
        array.add( ck8.isSelected() == true ? 1 : 0 );
        array.add( ck9.isSelected() == true ? 1 : 0 );
        array.add( ck10.isSelected() == true ? 1 : 0 );
        array.add( ck11.isSelected() == true ? 1 : 0 );
        array.add( ck12.isSelected() == true ? 1 : 0 );
        array.add( ck13.isSelected() == true ? 1 : 0 );
        array.add( ck14.isSelected() == true ? 1 : 0 );
        array.add( ck15.isSelected() == true ? 1 : 0 );
        array.add( ck16.isSelected() == true ? 1 : 0 );
        array.add( ck17.isSelected() == true ? 1 : 0 );
        array.add( ck18.isSelected() == true ? 1 : 0 );
        array.add( ck19.isSelected() == true ? 1 : 0 );
        array.add( ck20.isSelected() == true ? 1 : 0 );
        array.add( ck21.isSelected() == true ? 1 : 0 );
        array.add( ck22.isSelected() == true ? 1 : 0 );
        array.add( ck23.isSelected() == true ? 1 : 0 );
        array.add( ck24.isSelected() == true ? 1 : 0 );
        array.add( ck25.isSelected() == true ? 1 : 0 );
        
        return array;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JCheckBox ck1;
    private javax.swing.JCheckBox ck10;
    private javax.swing.JCheckBox ck11;
    private javax.swing.JCheckBox ck12;
    private javax.swing.JCheckBox ck13;
    private javax.swing.JCheckBox ck14;
    private javax.swing.JCheckBox ck15;
    private javax.swing.JCheckBox ck16;
    private javax.swing.JCheckBox ck17;
    private javax.swing.JCheckBox ck18;
    private javax.swing.JCheckBox ck19;
    private javax.swing.JCheckBox ck2;
    private javax.swing.JCheckBox ck20;
    private javax.swing.JCheckBox ck21;
    private javax.swing.JCheckBox ck22;
    private javax.swing.JCheckBox ck23;
    private javax.swing.JCheckBox ck24;
    private javax.swing.JCheckBox ck25;
    private javax.swing.JCheckBox ck3;
    private javax.swing.JCheckBox ck4;
    private javax.swing.JCheckBox ck5;
    private javax.swing.JCheckBox ck6;
    private javax.swing.JCheckBox ck7;
    private javax.swing.JCheckBox ck8;
    private javax.swing.JCheckBox ck9;
    private javax.swing.ButtonGroup grupoFase;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioExecucao;
    private javax.swing.JRadioButton radioTreinamento;
    private javax.swing.JTextField txtPadrao;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextArea txtServidor;
    // End of variables declaration//GEN-END:variables
}
