/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mrodrigues
 */
public class frmRna extends javax.swing.JFrame {

    /**
     * Creates new form frmRna
     */
    public frmRna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parâmetros", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pixels", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(5, 5));

        jCheckBox1.setMaximumSize(new java.awt.Dimension(61, 61));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(61, 61));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(61, 61));
        jPanel1.add(jCheckBox1);

        jCheckBox2.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox2.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox2.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox2);

        jCheckBox3.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox3.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox3.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox3);

        jCheckBox4.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox4.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox4.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox4);

        jCheckBox5.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox5.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox5.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox5);

        jCheckBox6.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox6.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox6.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox6);

        jCheckBox7.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox7.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox7.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox7);

        jCheckBox8.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox8.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox8.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox8);

        jCheckBox9.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox9.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox9.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox9);

        jCheckBox10.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox10.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox10.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox10);

        jCheckBox11.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox11.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox11.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox11);

        jCheckBox12.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox12.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox12.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox12);

        jCheckBox13.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox13.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox13.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox13);

        jCheckBox14.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox14.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox14.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox14);

        jCheckBox15.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox15.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox15.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox15);

        jCheckBox16.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox16.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox16.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox16);

        jCheckBox17.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox17.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox17.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox17);

        jCheckBox18.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox18.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox18.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox18);

        jCheckBox19.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox19.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox19.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox19);

        jCheckBox20.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox20.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox20.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox20);

        jCheckBox21.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox21.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox21.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox21);

        jCheckBox22.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox22.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox22.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox22);

        jCheckBox23.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox23.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox23.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox23);

        jCheckBox24.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox24.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox24.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox24);

        jCheckBox25.setMaximumSize(new java.awt.Dimension(31, 31));
        jCheckBox25.setMinimumSize(new java.awt.Dimension(31, 31));
        jCheckBox25.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(jCheckBox25);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fase", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jRadioButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jRadioButton1.setText("Execução");
        jPanel3.add(jRadioButton1, java.awt.BorderLayout.CENTER);

        jRadioButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jRadioButton2.setText("Treinamento");
        jPanel3.add(jRadioButton2, java.awt.BorderLayout.PAGE_START);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("Padrão:");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("Resultado:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton1.setText("Enviar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1)
                            .addComponent(jButton1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servidor", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
